server:
  port: 8091
spring:
  application:
    name: service-order
  zipkin:
    base-url: http://47.101.36.181:9411/ #zipkin server的请求地址
    discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
    sleuth:
      sampler:
        probability: 1.0 #采样的百分比
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.101.36.181:33060/springcloudalibabashop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 90-=uiop
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update # jpa根据实体类自动创建数据表
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect # mysql语法方言
  cloud:
    nacos:
      discovery:
        server-addr: 47.101.36.181:8818
service-product: # nacos调用的提供者的名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

rocketmq:
  name-server: 47.101.36.181:9876
  producer:
    group: test
