server:
  port: 8091
#  tomcat:
#    max-threads: 10 #tomcat的最大并发值修改为10,默认是200

spring:
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.101.36.181:33060/springcloudalibabashop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 90-=uiop
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update # jpa根据实体类自动创建数据表
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect # mysql语法方言
  cloud:
    nacos:
      discovery:
        server-addr: 47.101.36.181:8818
    sentinel:
      transport:
        port: 9999 #跟控制台交流的端口,随意指定一个未使用的端口即可
        dashboard: 127.0.0.1:8080 # 指定控制台服务的地址

service-product: # nacos调用的提供者的名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule