server:
  port: 8081
spring:
  application:
    name: service-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.99.47.236:3306/springcloudalibabashop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 90-=uiop
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update # jpa根据实体类自动创建数据表
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect # mysql语法方言
  cloud:
    nacos:
      discovery:
        server-addr: 47.99.47.236:8848