server:
  port: 8081
spring:
  application:
    name: service-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.101.36.181:33060/springcloudalibabashop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 90-=uiop
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update # jpa根据实体类自动创建数据表
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect # mysql语法方言
  cloud:
    nacos:
      discovery:
        server-addr: 47.101.36.181:8818