#server:
#  port: 8081
#spring:
#  zipkin:
#    base-url: http://192.168.7.16:9411/ #zipkin server的请求地址
#    discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
#    sleuth:
#      sampler:
#        probability: 1.0 #采样的百分比
#  application:
#    name: service-product
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.7.16:3306/springcloudalibabashop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
#    username: root
#    password: 90-=uiop
#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update # jpa根据实体类自动创建数据表
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect # mysql语法方言
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.7.16:8848
